// Dumps golden vectors from the JS engine for the C# port to verify against.
//   node test/make-golden.js
// Writes Assets/StreamingAssets/Trax/trax-golden.txt.
//
// WHY BIT PATTERNS, NOT DECIMALS: pattern generation uses only +, -, *, / and
// comparisons, all of which IEEE-754 requires to be correctly rounded — so JS
// and C# must agree to the last bit, and anything less would hide a real drift.
// (Math.pow is NOT guaranteed identical across implementations, which is why
// the pow-derived audio params are compared with a tolerance. None of them feed
// pattern generation.)
//
// A case is a whole TRACK — dials, key, six presets and six variations —
// because that is what a cassette will store. Covering only the dials would
// leave the entire part-choosing layer unverified.

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { computeParams } from '../engine/params.js';
import { generatePatterns, VOICES, MELODIC, BARS, STEPS } from '../engine/patterns.js';
import { classify } from '../engine/classifier.js';
import * as TRACK from '../engine/track.js';
import * as PRESETS from '../engine/presets.js';

const HERE = dirname (fileURLToPath (import.meta.url));
const OUT_DIR = join (HERE, '..', '..', '..', 'Assets', 'StreamingAssets', 'Trax');

const dv = new DataView (new ArrayBuffer (8));
function bits (x) {
    dv.setFloat64 (0, x);                       // big-endian, matches C# Int64 hex
    let s = '';
    for (let i = 0; i < 8; i++) s += dv.getUint8 (i).toString (16).padStart (2, '0');
    return s;
}

function hashString (s) {
    let h = 0x811c9dc5 >>> 0;
    for (let i = 0; i < s.length; i++) {
        h ^= s.charCodeAt (i) & 0xff;
        h = Math.imul (h, 0x01000193) >>> 0;
    }
    return h >>> 0;
}

function voiceDigest (bars, voice) {
    const melodic = MELODIC.indexOf (voice) !== -1;
    const parts = [];
    for (let b = 0; b < BARS; b++)
        for (let s = 0; s < STEPS; s++) {
            const st = bars[b][s];
            if (!st) { parts.push ('-'); continue; }
            parts.push ([
                bits (st.vel),
                bits (st.nudge),
                melodic ? String (st.degree) : 'x',
                melodic ? String (st.dur) : 'x',
                st.open ? '1' : '0'
            ].join (','));
        }
    // ';' not '|' — '|' is the field separator on every line.
    return parts.join (';');
}

// --- cases ---------------------------------------------------------------
// Walk each dial, then every module preset, a spread of variations, the keys,
// and a few awkward combinations. Every layer that can change the sound has to
// appear somewhere here or the port is only half-checked.
const CASES = [];
const push = (t) => CASES.push (TRACK.cloneTrack (t));

for (const key of ['pulse', 'crunch', 'goo', 'void', 'jitter', 'warp'])
    for (const v of [0, 3.5, 7, 10]) {
        const t = TRACK.defaultTrack ();
        t.dials[key] = v;
        push (t);
    }

for (const m of PRESETS.MODULE_NAMES)
    for (let pi = 0; pi < PRESETS.PRESET_COUNT; pi++)
        push (TRACK.setPreset (TRACK.defaultTrack (), m, pi));

for (const m of PRESETS.MODULE_NAMES)
    for (const vi of [1, 4, 7])
        push (TRACK.setVariation (TRACK.defaultTrack (), m, vi));

for (let k = 0; k < 12; k += 3) push (TRACK.setKey (TRACK.defaultTrack (), k));

{
    let t = TRACK.defaultTrack ();
    t.dials = { pulse: 10, crunch: 10, goo: 10, void: 10, jitter: 10, warp: 10 };
    for (const m of PRESETS.MODULE_NAMES) t = TRACK.setPreset (t, m, 4);
    for (const m of PRESETS.MODULE_NAMES) t = TRACK.setVariation (t, m, 7);
    push (TRACK.setKey (t, 11));
}
{
    const t = TRACK.defaultTrack ();
    t.dials = { pulse: 0, crunch: 0, goo: 0, void: 0, jitter: 0, warp: 0 };
    push (t);
}
{
    let t = TRACK.defaultTrack ();
    t.dials = { pulse: 6.5, crunch: 2.5, goo: 8.5, void: 1.5, jitter: 9.5, warp: 3.5 };
    t = TRACK.setPreset (t, 'THUMPER', 3);
    t = TRACK.setPreset (t, 'MOSS', 2);
    t = TRACK.setVariation (t, 'SIREN', 5);
    push (TRACK.setKey (t, 7));
}
push (TRACK.defaultTrack ());

const lines = [
    '# TRAX golden vectors — generated by prototypes/shuttle-computer/test/make-golden.js',
    '# Verifies the C# engine port matches the browser prototype EXACTLY.',
    '# Regenerate whenever engine/ changes. A diff here means every cassette',
    '# printed before the change would sound different after it.',
    '#',
    '# TRACK |i|pulse|crunch|goo|void|jitter|warp|key',
    '# PRESET|i|<one preset index per module, in META modules order>',
    '# VAR   |i|<one variation index per module, in META modules order>',
    '# ID    |i|trackId|scaleIdx|genre',
    '# EXACT |i|density|bpm|syncopation|nudgeSeconds|hatScatter|caveSend|caveFeedback|detuneCents  (IEEE754 bits, big-endian hex)',
    '# APPROX|i|filterBase|filterQ|lfoRate|lfoDepthOct                                            (Math.pow-derived, tolerance)',
    '# HASH  |i|<one FNV-1a of the voice digest per voice, in META voices order>',
    '# DIGEST|i|voice|digest                                                                      (case 0 only, to localise a mismatch)',
    '#',
    'META|bars=' + BARS + '|steps=' + STEPS + '|voices=' + VOICES.join (',') +
        '|modules=' + PRESETS.MODULE_NAMES.join (',') + '|cases=' + CASES.length
];

CASES.forEach ((t, i) => {
    const p = computeParams (t.dials, t.key);
    const pat = generatePatterns (t, p);
    const g = classify (t.dials);
    const d = t.dials;

    lines.push ('TRACK|' + i + '|' + d.pulse + '|' + d.crunch + '|' + d.goo + '|' +
                d.void + '|' + d.jitter + '|' + d.warp + '|' + t.key);
    lines.push ('PRESET|' + i + '|' + PRESETS.MODULE_NAMES.map (m => t.preset[m]).join ('|'));
    lines.push ('VAR|' + i + '|' + PRESETS.MODULE_NAMES.map (m => t.variation[m]).join ('|'));
    lines.push ('ID|' + i + '|' + TRACK.trackId (t) + '|' + p.scaleIdx + '|' + g.label);
    lines.push ('EXACT|' + i + '|' + [p.density, p.bpm, p.syncopation, p.nudgeSeconds,
                                      p.hatScatter, p.caveSend, p.caveFeedback, p.detuneCents]
                                     .map (bits).join ('|'));
    lines.push ('APPROX|' + i + '|' + [p.filterBase, p.filterQ, p.lfoRate, p.lfoDepthOct].join ('|'));
    lines.push ('HASH|' + i + '|' + VOICES.map (v => hashString (voiceDigest (pat[v], v))).join ('|'));
    if (i === 0)
        for (const v of VOICES) lines.push ('DIGEST|' + i + '|' + v + '|' + voiceDigest (pat[v], v));
});

mkdirSync (OUT_DIR, { recursive: true });
const path = join (OUT_DIR, 'trax-golden.txt');
writeFileSync (path, lines.join ('\n') + '\n');
console.log ('wrote ' + path);
console.log (CASES.length + ' cases, ' + VOICES.length + ' voice hashes each, ' + lines.length + ' lines');
