// Dumps golden vectors from the JS engine for the C# port to verify against.
//   node test/make-golden.js
// Writes Assets/StreamingAssets/Trax/trax-golden.json.
//
// WHY BIT PATTERNS, NOT DECIMALS: pattern generation uses only +, -, *, / and
// comparisons, all of which IEEE-754 requires to be correctly rounded — so JS
// and C# must agree to the last bit, and anything less than a bit-exact check
// would hide a real drift. (Math.pow is NOT guaranteed identical across
// implementations, which is why the pow-derived audio params below are compared
// with a tolerance instead. None of them feed pattern generation.)
//
// If this file and the C# engine ever disagree, a cassette printed in the
// browser prototype would sound different in-game. That is the whole point.

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { seedFromDials } from '../engine/prng.js';
import { computeParams } from '../engine/params.js';
import { generatePatterns, VOICES, BARS, STEPS } from '../engine/patterns.js';
import { classify } from '../engine/classifier.js';

const HERE = dirname (fileURLToPath (import.meta.url));
const OUT_DIR = join (HERE, '..', '..', '..', 'Assets', 'StreamingAssets', 'Trax');

const dv = new DataView (new ArrayBuffer (8));
function bits (x) {
    dv.setFloat64 (0, x);                       // big-endian, matches C# Int64 hex
    let s = '';
    for (let i = 0; i < 8; i++) s += dv.getUint8 (i).toString (16).padStart (2, '0');
    return s;
}

// Same FNV-1a the engine uses, over the ASCII of a digest string.
function hashString (s) {
    let h = 0x811c9dc5 >>> 0;
    for (let i = 0; i < s.length; i++) {
        h ^= s.charCodeAt (i) & 0xff;
        h = Math.imul (h, 0x01000193) >>> 0;
    }
    return h >>> 0;
}

function voiceDigest (bars) {
    const parts = [];
    for (let b = 0; b < BARS; b++)
        for (let s = 0; s < STEPS; s++) {
            const st = bars[b][s];
            if (!st) { parts.push ('-'); continue; }
            parts.push ([
                bits (st.vel),
                bits (st.nudge),
                st.degree === undefined ? 'x' : String (st.degree),
                st.dur === undefined ? 'x' : String (st.dur),
                st.open ? '1' : '0'
            ].join (','));
        }
    // ';' not '|' — '|' is the field separator on every line, and a digest that
    // contained it would silently shift every column to its right.
    return parts.join (';');
}

// A spread that walks each dial across its range and hits the corners, plus a
// few awkward interior points.
const CASES = [];
const base = { pulse: 5, crunch: 3, goo: 5, void: 4, jitter: 4, warp: 5 };
for (const key of ['pulse', 'crunch', 'goo', 'void', 'jitter', 'warp'])
    for (const v of [0, 3.5, 7, 10])
        CASES.push (Object.assign ({}, base, { [key]: v }));
CASES.push ({ pulse: 0, crunch: 0, goo: 0, void: 0, jitter: 0, warp: 0 });
CASES.push ({ pulse: 10, crunch: 10, goo: 10, void: 10, jitter: 10, warp: 10 });
CASES.push ({ pulse: 10, crunch: 0, goo: 10, void: 0, jitter: 10, warp: 0 });
CASES.push ({ pulse: 0, crunch: 10, goo: 0, void: 10, jitter: 0, warp: 10 });
CASES.push ({ pulse: 6.5, crunch: 2.5, goo: 8.5, void: 1.5, jitter: 9.5, warp: 3.5 });
CASES.push (Object.assign ({}, base));

// Flat, line-based, pipe-separated — NOT JSON. The C# side has to parse this
// without a JSON library (JsonUtility cannot express arbitrary keys, and a
// hand-rolled parser is code that can't be compile-tested here). Splitting on
// '|' cannot go subtly wrong.
const lines = [
    '# TRAX golden vectors — generated by prototypes/shuttle-computer/test/make-golden.js',
    '# Verifies the C# engine port matches the browser prototype EXACTLY.',
    '# Regenerate whenever engine/ changes. A diff here means every cassette',
    '# printed before the change would sound different after it.',
    '#',
    '# CASE  |i|pulse|crunch|goo|void|jitter|warp|seed|scaleIdx|genre',
    '# EXACT |i|density|bpm|syncopation|nudgeSeconds|hatScatter|caveSend|caveFeedback|detuneCents   (IEEE754 bits, big-endian hex — must match bit for bit)',
    '# APPROX|i|filterBase|filterQ|lfoRate|lfoDepthOct                                             (Math.pow-derived — compare with tolerance)',
    '# HASH  |i|kick|snare|hat|bass|lead                                                           (FNV-1a of the voice digest)',
    '# DIGEST|i|voice|digest                                                                       (case 0 only, for localising a mismatch)',
    '#',
    'META|bars=' + BARS + '|steps=' + STEPS + '|voices=' + VOICES.join (',') + '|cases=' + CASES.length
];

const cases = CASES.map ((dials, i) => {
    const seed = seedFromDials (dials);
    const p = computeParams (dials);
    const pat = generatePatterns (seed, p);
    const g = classify (dials);

    const voices = {};
    for (const v of VOICES) voices[v] = hashString (voiceDigest (pat[v]));

    return {
        index: i,
        dials,
        seed,
        scaleIdx: p.scaleIdx,
        genre: g.label,
        // Pure arithmetic — must match bit for bit.
        exact: {
            density: bits (p.density),
            bpm: bits (p.bpm),
            syncopation: bits (p.syncopation),
            nudgeSeconds: bits (p.nudgeSeconds),
            hatScatter: bits (p.hatScatter),
            caveSend: bits (p.caveSend),
            caveFeedback: bits (p.caveFeedback),
            detuneCents: bits (p.detuneCents)
        },
        // Math.pow-derived — compare with a relative tolerance.
        approx: {
            filterBase: p.filterBase,
            filterQ: p.filterQ,
            lfoRate: p.lfoRate,
            lfoDepthOct: p.lfoDepthOct
        },
        voiceHashes: voices,
        // One case carries its full digest so a mismatch can be localised
        // without regenerating anything.
        digests: i === 0 ? Object.fromEntries (VOICES.map (v => [v, voiceDigest (pat[v])])) : undefined
    };
});

for (const c of cases) {
    const d = c.dials;
    lines.push ('CASE|' + c.index + '|' + d.pulse + '|' + d.crunch + '|' + d.goo + '|' +
                d.void + '|' + d.jitter + '|' + d.warp + '|' + c.seed + '|' +
                c.scaleIdx + '|' + c.genre);
    const e = c.exact;
    lines.push ('EXACT|' + c.index + '|' + e.density + '|' + e.bpm + '|' + e.syncopation + '|' +
                e.nudgeSeconds + '|' + e.hatScatter + '|' + e.caveSend + '|' +
                e.caveFeedback + '|' + e.detuneCents);
    const a = c.approx;
    lines.push ('APPROX|' + c.index + '|' + a.filterBase + '|' + a.filterQ + '|' +
                a.lfoRate + '|' + a.lfoDepthOct);
    const h = c.voiceHashes;
    lines.push ('HASH|' + c.index + '|' + h.kick + '|' + h.snare + '|' + h.hat + '|' +
                h.bass + '|' + h.lead);
    if (c.digests)
        for (const v of VOICES) lines.push ('DIGEST|' + c.index + '|' + v + '|' + c.digests[v]);
}

mkdirSync (OUT_DIR, { recursive: true });
const path = join (OUT_DIR, 'trax-golden.txt');
writeFileSync (path, lines.join ('\n') + '\n');
console.log ('wrote ' + path);
console.log (cases.length + ' cases, ' + VOICES.length + ' voice hashes each, ' + lines.length + ' lines');
